title: Daniel Ashton's Projects
description: A page to display and categorise projects by me.
url: https://www.linkedin.com/in/danieljashton/
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight